title: "Kitimus"
description: "Parenting, tech, and surviving adulthood with minimal screaming."
theme: minima

url: "https://jwwhitsitt.github.io"
baseurl: ""

author:
  name: "Jeff"

markdown: kramdown
highlighter: rouge
paginate: 5

plugins:
  - jekyll-paginate
