title: "Jeff Whitsitt"
name: "Jeff Whitsitt"
description: "Clear, conversational writing about technology, systems, and real world problem solving. No buzzwords. No filler."
url: "https://jeffwhitsitt.com"
baseurl: ""

remote_theme: "mmistakes/minimal-mistakes"

# Dark theme skin
minimal_mistakes_skin: "dark"

logo: "/assets/images/jw.png"

lang: "en-US"

author:
  name: "Jeff Whitsitt"
  avatar: "/assets/images/jw.png"
  bio: "Tech-minded writer who explains complex stuff in plain English. I build things, document what I learn, and write like a human."
  location: "Fort Wayne, IN"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:contact@jeffwhitsitt.com"
    - label: "Text or voicemail"
      icon: "fas fa-fw fa-phone"
      url: "tel:+12602228509"

# Collections
collections:
  pages:
    output: true
    permalink: /:path/

# Defaults (Global layout behavior)
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      sidebar: false
      read_time: true
      comments: false
      share: true
      related: true

  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: false
      sidebar: false

paginate: 5
paginate_path: "/page:num/"

# Plugins allowed on GitHub Pages
plugins:
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-seo-tag
